version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - ./db/.env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
