version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - ./.env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  frontend:
    image: node
    command: npm build && npm start
    ports:
      - 5000:5000
    restart: always

  backend:
    image: node
    command: npm build && npm start
    ports:
      - 80:80
    restart: always